module ConfigTypes 

export NonMPIConfig

struct NonMPIConfig
    data_path::String
    analysis_path::String
    nIter::Int
    seed::Int
    nrank::Int
    annot_file::String
    annot_dict::String
    out_freq::Int
    starting_value_dir::String
    gscale_value_dir::String
    st_path::String
    thin::Int
    n1::Int
    n2::Int
    n_con::Int
    estimate_vare::Bool
    estimate_vara::Bool
    estimate_pi::Bool
    estimate_Gscale::Bool
    estGscale_iter::Int
    report_pleiotropic_qtl_effect_matrix::Bool
    output_mcmc_delta::Bool
    is_continue::Bool
end

function NonMPIConfig(
    data_path::String,
    analysis_path::String,
    nIter::Int,
    seed::Int,
    nrank::Int,
    annot_file::String,
    annot_dict::String,
    out_freq::Int,
    starting_value_dir::String,
    gscale_value_dir::String,
    st_path::String,
    thin::Int,
    n1::Int,
    n2::Int,
    is_continue::Bool;
    n_con::Int=0,
    estimate_vare::Bool=true,
    estimate_vara::Bool=true,
    estimate_pi::Bool=true,
    estimate_Gscale::Bool=true,
    estGscale_iter::Int=500,
    report_pleiotropic_qtl_effect_matrix::Bool=true,
    output_mcmc_delta::Bool=true,
)
    return NonMPIConfig(
        data_path,
        analysis_path,
        nIter,
        seed,
        nrank,
        annot_file,
        annot_dict,
        out_freq,
        starting_value_dir,
        gscale_value_dir,
        st_path,
        thin,
        n1,
        n2,
        n_con,
        estimate_vare,
        estimate_vara,
        estimate_pi,
        estimate_Gscale,
        estGscale_iter,
        report_pleiotropic_qtl_effect_matrix,
        output_mcmc_delta,
        is_continue,
    )
end

function NonMPIConfig(
    data_path::String,
    analysis_path::String,
    nIter::Int,
    seed::Int,
    nrank::Int,
    annot_file::String,
    annot_dict::String,
    out_freq::Int,
    starting_value_dir::String,
    gscale_value_dir::String,
    st_path::String,
    thin::Int,
    n1::Int,
    n2::Int,
    n_con::Int,
    is_continue::Bool;
    estimate_vare::Bool=true,
    estimate_vara::Bool=true,
    estimate_pi::Bool=true,
    estimate_Gscale::Bool=true,
    estGscale_iter::Int=500,
    report_pleiotropic_qtl_effect_matrix::Bool=true,
    output_mcmc_delta::Bool=true,
)
    return NonMPIConfig(
        data_path,
        analysis_path,
        nIter,
        seed,
        nrank,
        annot_file,
        annot_dict,
        out_freq,
        starting_value_dir,
        gscale_value_dir,
        st_path,
        thin,
        n1,
        n2,
        n_con,
        estimate_vare,
        estimate_vara,
        estimate_pi,
        estimate_Gscale,
        estGscale_iter,
        report_pleiotropic_qtl_effect_matrix,
        output_mcmc_delta,
        is_continue,
    )
end

end